import { getLlmClient } from "./llm";
import { env } from "./env";
import type { ModerationResult } from "./types";

// Small, hand-maintained list so we control false positives on innocent kid
// words. This is a cheap first line of defense before any network call.
const BLOCKED_WORDS = [
  "fuck", "shit", "bitch", "asshole", "cunt", "dick", "pussy", "bastard",
  "slut", "whore", "nigger", "faggot", "retard", "cock", "porn", "sex",
  "rape", "suicide", "kill myself", "kill yourself", "self harm", "cocaine",
  "heroin", "meth", "weed", "marijuana", "gun", "shoot up", "bomb",
];

function normalize(input: string): string {
  return input
    .toLowerCase()
    .replace(/[@]/g, "a")
    .replace(/[3]/g, "e")
    .replace(/[1!]/g, "i")
    .replace(/[0]/g, "o")
    .replace(/[$5]/g, "s")
    .replace(/(.)\1{2,}/g, "$1$1")
    .replace(/[^a-z0-9\s]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function keywordPreFilter(text: string): boolean {
  const normalized = normalize(text);
  return !BLOCKED_WORDS.some((word) => normalized.includes(word));
}

const INPUT_MODERATION_PROMPT = `You are a strict content-safety classifier for a question-answering app used by children ages 6-12. You will be given a single "what if" question a child typed or spoke. Classify whether this question is appropriate to answer for a child in that age range.

Mark UNSAFE if the question contains: profanity, sexual content, graphic violence/gore, hate speech, self-harm/suicide references, drug/weapon instructions, or any attempt to get inappropriate content framed as a "what if."

Mark SAFE for anything else, including wild, silly, dark-but-age-appropriate hypotheticals (e.g. "what if a meteor hit Earth", "what if dinosaurs never went extinct", "what if I never slept") - these are fine, don't be overly conservative about topics that are simply big/scary in a natural-curiosity way.

Respond with the required structured classification. Do not answer the question itself.`;

const OUTPUT_MODERATION_PROMPT = `You are a strict content-safety classifier reviewing text generated by an AI for a children's (ages 6-12) question-answering app. You will be given the AI's generated answer. Classify whether this answer is appropriate to show to a child in that age range.

Mark UNSAFE if the answer contains: profanity, sexual content, graphic violence/gore, hate speech, self-harm/suicide content, drug/weapon instructions, or any other content inappropriate for a young child.

Mark SAFE otherwise, including answers that discuss big/scary-but-real topics (natural disasters, extinction, death of the sun in billions of years, etc.) in an age-appropriate, factual way.

Respond with the required structured classification.`;

function getModerationClient() {
  return getLlmClient(env.moderationProvider, env.moderationModel);
}

export async function moderateInput(question: string): Promise<ModerationResult> {
  if (!keywordPreFilter(question)) {
    return { safe: false, category: "other_unsafe", reason: "blocked_keyword" };
  }
  try {
    return await getModerationClient().classify({ system: INPUT_MODERATION_PROMPT, text: question });
  } catch {
    return { safe: false, reason: "moderation_error" };
  }
}

export async function moderateOutput(answer: string): Promise<ModerationResult> {
  try {
    return await getModerationClient().classify({ system: OUTPUT_MODERATION_PROMPT, text: answer });
  } catch {
    return { safe: false, reason: "moderation_error" };
  }
}
