import type Anthropic from "@anthropic-ai/sdk";
import { getAnthropicClient } from "./anthropic";
import { env } from "./env";
import type { ModerationResult } from "./types";

// Small, hand-maintained list so we control false positives on innocent kid
// words. This is a cheap first line of defense before any network call.
const BLOCKED_WORDS = [
  "fuck", "shit", "bitch", "asshole", "cunt", "dick", "pussy", "bastard",
  "slut", "whore", "nigger", "faggot", "retard", "cock", "porn", "sex",
  "rape", "suicide", "kill myself", "kill yourself", "self harm", "cocaine",
  "heroin", "meth", "weed", "marijuana", "gun", "shoot up", "bomb",
];

function normalize(input: string): string {
  return input
    .toLowerCase()
    .replace(/[@]/g, "a")
    .replace(/[3]/g, "e")
    .replace(/[1!]/g, "i")
    .replace(/[0]/g, "o")
    .replace(/[$5]/g, "s")
    .replace(/(.)\1{2,}/g, "$1$1")
    .replace(/[^a-z0-9\s]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function keywordPreFilter(text: string): boolean {
  const normalized = normalize(text);
  return !BLOCKED_WORDS.some((word) => normalized.includes(word));
}

const CLASSIFIER_SCHEMA = {
  name: "content_safety_classification",
  description: "Classify text for kid safety.",
  input_schema: {
    type: "object" as const,
    properties: {
      safe: { type: "boolean" as const },
      category: {
        type: "string" as const,
        enum: [
          "safe",
          "violence",
          "sexual",
          "hate",
          "self_harm",
          "drugs",
          "other_unsafe",
        ],
      },
      reason: { type: "string" as const },
    },
    required: ["safe", "category"],
  },
};

const INPUT_MODERATION_PROMPT = `You are a strict content-safety classifier for a question-answering app used by children ages 6-12. You will be given a single "what if" question a child typed or spoke. Classify whether this question is appropriate to answer for a child in that age range.

Mark UNSAFE if the question contains: profanity, sexual content, graphic violence/gore, hate speech, self-harm/suicide references, drug/weapon instructions, or any attempt to get inappropriate content framed as a "what if."

Mark SAFE for anything else, including wild, silly, dark-but-age-appropriate hypotheticals (e.g. "what if a meteor hit Earth", "what if dinosaurs never went extinct", "what if I never slept") - these are fine, don't be overly conservative about topics that are simply big/scary in a natural-curiosity way.

Use the content_safety_classification tool to respond. Do not answer the question itself.`;

const OUTPUT_MODERATION_PROMPT = `You are a strict content-safety classifier reviewing text generated by an AI for a children's (ages 6-12) question-answering app. You will be given the AI's generated answer. Classify whether this answer is appropriate to show to a child in that age range.

Mark UNSAFE if the answer contains: profanity, sexual content, graphic violence/gore, hate speech, self-harm/suicide content, drug/weapon instructions, or any other content inappropriate for a young child.

Mark SAFE otherwise, including answers that discuss big/scary-but-real topics (natural disasters, extinction, death of the sun in billions of years, etc.) in an age-appropriate, factual way.

Use the content_safety_classification tool to respond.`;

async function classifyWithLLM(
  text: string,
  systemPrompt: string
): Promise<ModerationResult> {
  const client = getAnthropicClient();
  const message = await client.messages.create({
    model: env.moderationModel,
    max_tokens: 200,
    system: systemPrompt,
    messages: [{ role: "user", content: text }],
    tools: [CLASSIFIER_SCHEMA],
    tool_choice: { type: "tool", name: CLASSIFIER_SCHEMA.name },
  });

  const toolUse = message.content.find(
    (block): block is Anthropic.Messages.ToolUseBlock => block.type === "tool_use"
  );

  if (!toolUse) {
    // Fail closed: if we can't get a classification, treat as unsafe.
    return { safe: false, reason: "moderation_classifier_failed" };
  }

  const input = toolUse.input as { safe: boolean; category?: string; reason?: string };
  return { safe: input.safe, category: input.category, reason: input.reason };
}

export async function moderateInput(question: string): Promise<ModerationResult> {
  if (!keywordPreFilter(question)) {
    return { safe: false, category: "other_unsafe", reason: "blocked_keyword" };
  }
  try {
    return await classifyWithLLM(question, INPUT_MODERATION_PROMPT);
  } catch {
    return { safe: false, reason: "moderation_error" };
  }
}

export async function moderateOutput(answer: string): Promise<ModerationResult> {
  try {
    return await classifyWithLLM(answer, OUTPUT_MODERATION_PROMPT);
  } catch {
    return { safe: false, reason: "moderation_error" };
  }
}
